### ISSUE TITLE
Yenom's cool storage video tutorial series

### ISSUE THREAD

**Issue by atweiden** [ecdsa/electrum-web#39]
![cool storage](http://i.imgur.com/uR4GLNt.png)

Any thoughts on how to put videos tutorials on the website? I think yenom is willing to do more of them besides cool storage, which is a very good series.

**Comment by ecdsa** [comment]
just embed them from youtube and create a PR here.

**Comment by ecdsa** [comment]
documentation is being moved to a wiki:
https://electrum.orain.org/wiki/Main_Page
