### ISSUE TITLE
Electrum Wiki link redirects to porn site

### ISSUE THREAD

**Issue by jonathancross** [ecdsa/electrum-web#47]
Wiki URL:  http://electrum.orain.org

Headers:

```
HTTP/1.1 301 Moved Permanently
Server: nginx
Date: Thu, 17 Sep 2015 11:57:11 GMT
Content-Type: text/html; charset=UTF-8
Transfer-Encoding: chunked
Location: http://www.pornhub.com/
Vary: User-Agent
Rating: RTA-5042-1996-1400-1577-RTA
```

Links found here:
- https://en.bitcoin.it/wiki/Electrum/Documentation
- https://electrum.org/#community
- https://electrum.org/#documentation

Note: Unfortunately the code here in GitHub doesn't seem to match what is live, so I cannot create pull request.

**Comment by ecdsa** [comment]
thanks, I will move this documentation elsewhere.

**Comment by revi** [comment]
If you wish, electrumwiki full dump (backup of contents, without file. Just history of the all pages) as of June 15 is available per request. See [their statement](https://orainblog.wordpress.com/2015/09/25/orain-compromise-initial-statement/).

> Assuming the worst, though, we do have complete backups for all wikis that existed on 15 June 2015, and we will be happy to give those to people who request them.

It is linked on freenode #orain topic, which was advertised as official channel for orain when it was alive. So this is really an official statement.

**Comment by ecdsa** [comment]
documentation was moved to docs.electrum.org
