### ISSUE TITLE
Electrum.org does not match code here in GitHub

### ISSUE THREAD

**Issue by jonathancross** [ecdsa/electrum-web#50]
Seems GitHub has not been updated since 2014, but electrum.org has much newer files (home page reports lastmod as `Mon, 18 Apr 2016 16:40:31 GMT` and diff also indicates home page is completely different).  Curiously, the website used very old XHTML whereas GitHub uses the modern HTML5.

Would be great to have current website code dumped here **_replacing_** whatever this is.  The we can contribute  :-)

**Comment by jidanni** [comment]
At the bottom of https://electrum.org/ a link "website source" points to http://github.com/ecdsa/electrum-web but that is not apparently the current version. At least I cannot find e.g., https://electrum.org/bcc2.txt on GitHub.
